# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2.1

workflows:
  my-workflow:
    jobs:
      - run-tests:
          context:
            - dockerhub-rcsheets

jobs:
  run-tests:
    docker:
      - image: cimg/php:7.4
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: cimg/mysql:8.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          MYSQL_ROOT_PASSWORD: mooph5oomiuRe5Shoj
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: ego7Ligiegh4Azo0ei
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in $(seq 1 10)
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Gave up waiting for MySQL && exit 1
      - run:
          name: Run tests
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client subversion
            ./bin/install-wp-tests.sh test_db test_user ego7Ligiegh4Azo0ei 127.0.0.1 latest true
            composer update
            ./vendor/bin/phpunit
            WP_MULTISITE=1 ./vendor/bin/phpunit
