# PHP CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-php/
version: 2

jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - run: php --version
